<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Production;

use App\Services\AI\AFOS\Types\ShotStatus;

final class ProductionState
{
    public function __construct(
        public readonly string $shotId,
        public readonly ShotStatus $status,
        public readonly ?string $lockedAt,
        public readonly ?string $failureReason,
        public readonly int $retryCount,
        public readonly array $decisionTrace,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            shotId: $data['shotId'],
            status: ShotStatus::from($data['status']),
            lockedAt: $data['lockedAt'] ?? null,
            failureReason: $data['failureReason'] ?? null,
            retryCount: $data['retryCount'],
            decisionTrace: $data['decisionTrace'] ?? [],
        );
    }

    public function toArray(): array
    {
        return [
            'shotId' => $this->shotId,
            'status' => $this->status->value,
            'lockedAt' => $this->lockedAt,
            'failureReason' => $this->failureReason,
            'retryCount' => $this->retryCount,
            'decisionTrace' => $this->decisionTrace,
        ];
    }}
