<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Creative;

final class CinematographyProfile
{
    public function __construct(
        public readonly string $name,
        public readonly array $lensVocabularyMm,
        public readonly string $lightingStyle,
        public readonly string $motionStyle,
        public readonly int $depthLayersPreferred,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            lensVocabularyMm: $data['lensVocabularyMm'] ?? [],
            lightingStyle: $data['lightingStyle'],
            motionStyle: $data['motionStyle'],
            depthLayersPreferred: $data['depthLayersPreferred'],
        );
    }

    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'lensVocabularyMm' => $this->lensVocabularyMm,
            'lightingStyle' => $this->lightingStyle,
            'motionStyle' => $this->motionStyle,
            'depthLayersPreferred' => $this->depthLayersPreferred,
        ];
    }}
