<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Creative;

use App\Services\AI\AFOS\Types\Domain;
use App\Services\AI\AFOS\Types\Audience;
use App\Services\AI\AFOS\Types\Platform;
use App\Services\AI\AFOS\Types\ProductionGoal;

final class CreativeBrief
{
    public function __construct(
        public readonly Domain $domain,
        public readonly string $subDomain,
        public readonly Audience $audience,
        public readonly string $brand,
        public readonly Platform $platform,
        public readonly int $durationSec,
        public readonly ProductionGoal $goal,
        public readonly array $constraints,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            domain: Domain::from($data['domain']),
            subDomain: $data['subDomain'],
            audience: Audience::from($data['audience']),
            brand: $data['brand'],
            platform: Platform::from($data['platform']),
            durationSec: $data['durationSec'],
            goal: ProductionGoal::from($data['goal']),
            constraints: $data['constraints'] ?? [],
        );
    }

    public function toArray(): array
    {
        return [
            'domain' => $this->domain->value,
            'subDomain' => $this->subDomain,
            'audience' => $this->audience->value,
            'brand' => $this->brand,
            'platform' => $this->platform->value,
            'durationSec' => $this->durationSec,
            'goal' => $this->goal->value,
            'constraints' => $this->constraints,
        ];
    }}
