<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Creative;

use App\Services\AI\AFOS\Types\CutFrequency;
use App\Services\AI\AFOS\Types\CameraPhilosophy;
use App\Services\AI\AFOS\Types\ColorPhilosophy;

final class DirectorProfile
{
    public function __construct(
        public readonly string $name,
        public readonly float $observationWeight,
        public readonly float $motionWeight,
        public readonly float $revealWeight,
        public readonly float $negativeSpaceWeight,
        public readonly float $symmetryWeight,
        public readonly CutFrequency $cutFrequency,
        public readonly CameraPhilosophy $cameraPhilosophy,
        public readonly ColorPhilosophy $colorPhilosophy,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            observationWeight: $data['observationWeight'],
            motionWeight: $data['motionWeight'],
            revealWeight: $data['revealWeight'],
            negativeSpaceWeight: $data['negativeSpaceWeight'],
            symmetryWeight: $data['symmetryWeight'],
            cutFrequency: CutFrequency::from($data['cutFrequency']),
            cameraPhilosophy: CameraPhilosophy::from($data['cameraPhilosophy']),
            colorPhilosophy: ColorPhilosophy::from($data['colorPhilosophy']),
        );
    }

    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'observationWeight' => $this->observationWeight,
            'motionWeight' => $this->motionWeight,
            'revealWeight' => $this->revealWeight,
            'negativeSpaceWeight' => $this->negativeSpaceWeight,
            'symmetryWeight' => $this->symmetryWeight,
            'cutFrequency' => $this->cutFrequency->value,
            'cameraPhilosophy' => $this->cameraPhilosophy->value,
            'colorPhilosophy' => $this->colorPhilosophy->value,
        ];
    }}
