<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Creative;

use App\Services\AI\AFOS\Types\Emotion;
use App\Services\AI\AFOS\Types\Narrative;
use App\Services\AI\AFOS\Types\Tempo;
use App\Services\AI\AFOS\Types\Experience;

final class Intent
{
    public function __construct(
        public readonly Emotion $primaryEmotion,
        public readonly ?Emotion $secondaryEmotion,
        public readonly Narrative $narrative,
        public readonly Tempo $tempo,
        public readonly Experience $viewerExperience,
        public readonly string $desiredTakeaway,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            primaryEmotion: Emotion::from($data['primaryEmotion']),
            secondaryEmotion: isset($data['secondaryEmotion']) ? Emotion::from($data['secondaryEmotion']) : null,
            narrative: Narrative::from($data['narrative']),
            tempo: Tempo::from($data['tempo']),
            viewerExperience: Experience::from($data['viewerExperience']),
            desiredTakeaway: $data['desiredTakeaway'],
        );
    }

    public function toArray(): array
    {
        return [
            'primaryEmotion' => $this->primaryEmotion->value,
            'secondaryEmotion' => $this->secondaryEmotion?->value,
            'narrative' => $this->narrative->value,
            'tempo' => $this->tempo->value,
            'viewerExperience' => $this->viewerExperience->value,
            'desiredTakeaway' => $this->desiredTakeaway,
        ];
    }}
