<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum Audience: string
{
    case ULTRA_HNWI = 'ultra_hnwi';
    case ASPIRATIONAL = 'aspirational';
    case MASS = 'mass';
    case ENTHUSIAST = 'enthusiast';
    case PROFESSIONAL = 'professional';
}
