<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum CameraHeight: string
{
    case GROUND = 'ground';
    case ANKLE = 'ankle';
    case KNEE = 'knee';
    case HIP = 'hip';
    case WAIST = 'waist';
    case CHEST = 'chest';
    case EYE = 'eye';
    case ABOVE_HEAD = 'above_head';
    case DRONE_LOW = 'drone_low';
    case DRONE_HIGH = 'drone_high';
}
