<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum CameraPhilosophy: string
{
    case SLOW_OBSERVATION = 'slow_observation';
    case DYNAMIC_TRACKING = 'dynamic_tracking';
    case FPV_EXPLORATION = 'fpv_exploration';
    case CINEMATIC_ORBIT = 'cinematic_orbit';
    case MACRO_INTIMACY = 'macro_intimacy';
    case ARCHITECTURAL_STATIC = 'architectural_static';
}
