<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum CameraMovementType: string
{
    case PUSH_IN = 'push_in';
    case PULL_OUT = 'pull_out';
    case TRACKING = 'tracking';
    case ORBIT = 'orbit';
    case CRANE_UP = 'crane_up';
    case CRANE_DOWN = 'crane_down';
    case STATIC = 'static';
    case FPV = 'fpv';
    case HANDHELD = 'handheld';
    case DRONE_DESCEND = 'drone_descend';
    case DRONE_ASCEND = 'drone_ascend';
}
