<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum ColorPhilosophy: string
{
    case WARM_GOLDEN = 'warm_golden';
    case COOL_BLUE = 'cool_blue';
    case NEUTRAL_DESATURATED = 'neutral_desaturated';
    case HIGH_CONTRAST = 'high_contrast';
    case SOFT_MUTED = 'soft_muted';
}
