<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum CompositionRule: string
{
    case RULE_OF_THIRDS = 'rule_of_thirds';
    case GOLDEN_RATIO = 'golden_ratio';
    case SYMMETRY = 'symmetry';
    case LEAD_ROOM = 'lead_room';
    case NEGATIVE_LEAD = 'negative_lead';
    case CENTER_WEIGHT = 'center_weight';
}
