<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum CutFrequency: string
{
    case MINIMAL = 'minimal';
    case SLOW = 'slow';
    case MEDIUM = 'medium';
    case FAST = 'fast';
    case AGGRESSIVE = 'aggressive';
}
