<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum DepthLayer: string
{
    case FOREGROUND = 'foreground';
    case MIDGROUND = 'midground';
    case BACKGROUND = 'background';
}
