<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum Domain: string
{
    case LUXURY_ARCHITECTURE = 'luxury_architecture';
    case SPORTS = 'sports';
    case SUPERYACHT = 'superyacht';
    case HYPERCAR = 'hypercar';
    case DOCUMENTARY = 'documentary';
    case FASHION = 'fashion';
    case AUTOMOTIVE = 'automotive';
    case ARCHITECTURE = 'architecture';
}
