<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum Emotion: string
{
    case SERENITY = 'serenity';
    case POWER = 'power';
    case WONDER = 'wonder';
    case TRIUMPH = 'triumph';
    case CURIOSITY = 'curiosity';
    case TENSION = 'tension';
    case LUXURY = 'luxury';
    case ISOLATION = 'isolation';
}
