<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum Experience: string
{
    case IMMERSION = 'immersion';
    case EXCITEMENT = 'excitement';
    case ASPIRATION = 'aspiration';
    case EDUCATION = 'education';
    case EMOTION = 'emotion';
}
