<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum EyeFlowDirection: string
{
    case LEFT_TO_RIGHT = 'left_to_right';
    case RIGHT_TO_LEFT = 'right_to_left';
    case TOP_TO_BOTTOM = 'top_to_bottom';
    case DIAGONAL_TL_BR = 'diagonal_tl_br';
    case DIAGONAL_TR_BL = 'diagonal_tr_bl';
    case CENTRIPETAL = 'centripetal';
}
