<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum FramingType: string
{
    case EXTREME_CLOSE = 'extreme_close';
    case CLOSE = 'close';
    case MEDIUM = 'medium';
    case WIDE = 'wide';
    case EXTREME_WIDE = 'extreme_wide';
}
