<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum GoalType: string
{
    case REVEAL = 'reveal';
    case ESTABLISH = 'establish';
    case FOLLOW = 'follow';
    case DISCOVER = 'discover';
    case TRANSITION = 'transition';
    case RESOLVE = 'resolve';
}
