<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum NarrativeFunction: string
{
    case ESTABLISH = 'establish';
    case BUILD = 'build';
    case REVEAL = 'reveal';
    case RESOLVE = 'resolve';
}
