<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum Narrative: string
{
    case REVEAL_BEAUTY = 'reveal_beauty';
    case DEMONSTRATE_POWER = 'demonstrate_power';
    case EVOKE_ASPIRATION = 'evoke_aspiration';
    case DOCUMENT_CRAFT = 'document_craft';
    case CAPTURE_MOMENT = 'capture_moment';
    case SHOW_SCALE = 'show_scale';
}
