<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum NegativeSpaceDirection: string
{
    case LEFT = 'left';
    case RIGHT = 'right';
    case TOP = 'top';
    case BOTTOM = 'bottom';
}
