<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum Platform: string
{
    case YOUTUBE = 'youtube';
    case INSTAGRAM_REEL = 'instagram_reel';
    case CINEMA = 'cinema';
    case OOH = 'ooh';
    case BRAND_SITE = 'brand_site';
}
