<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum ProductionGoal: string
{
    case SHOWCASE = 'showcase';
    case INSPIRE = 'inspire';
    case DOCUMENT = 'document';
    case SELL = 'sell';
    case ANNOUNCE = 'announce';
}
