<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum ShotStatus: string
{
    case PLANNED = 'planned';
    case COMPILED = 'compiled';
    case QUEUED = 'queued';
    case RENDERING = 'rendering';
    case RENDERED = 'rendered';
    case QA_PENDING = 'qa_pending';
    case QA_PASSED = 'qa_passed';
    case QA_FAILED = 'qa_failed';
    case LOCKED = 'locked';
    case REVISION_NEEDED = 'revision_needed';
}
