<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Types;

enum Tempo: string
{
    case MEDITATIVE = 'meditative';
    case MEASURED = 'measured';
    case BUILDING = 'building';
    case URGENT = 'urgent';
    case EXPLOSIVE = 'explosive';
}
