<?php

namespace App\Services\AI\SceneGraph\Nodes;

/**
 * Resolved event-driven timeline for a single shot.
 *
 * phases is PhaseNode[] — fully typed, no raw arrays.
 * emotionCurve is EmotionPoint[] — generated by TimelineResolver from action
 * phase structure + emotion code. Sprint 6 will add Bezier-fitted curves.
 *
 * Note: count() and totalDuration() are kept as node methods because they are
 * pure derived values of the node's own data, not business logic. If analysis
 * beyond simple reads is needed, use TimelineInspector (Sprint 6).
 */
final class TimelineNode
{
    /**
     * @param PhaseNode[]    $phases
     * @param EmotionPoint[] $emotionCurve
     */
    public function __construct(
        public readonly array $phases,
        public readonly array $emotionCurve = [],
    ) {}

    /** Build from raw phase arrays (e.g. from MotionPlanner + enrichTimeline). */
    public static function fromArray(array $rawPhases): self
    {
        return new self(
            phases: array_map(fn(array $p) => PhaseNode::from($p), $rawPhases),
        );
    }

    public function toArray(): array
    {
        return array_map(fn(PhaseNode $p) => $p->toArray(), $this->phases);
    }

    /** Total clip duration derived from the last phase end time. */
    public function totalDuration(): float
    {
        if (empty($this->phases)) {
            return 0.0;
        }
        return (float) $this->phases[count($this->phases) - 1]->end;
    }

    public function count(): int
    {
        return count($this->phases);
    }
}
