<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Ir;

use App\Services\AI\AFOS\Types\DOFLevel;
use App\Services\AI\AFOS\Types\CameraHeight;
use App\Services\AI\AFOS\Types\CameraMovementType;
use App\Services\AI\AFOS\Types\FramingType;

final class CameraIR
{
    public function __construct(
        public readonly string $shotId,
        public readonly int $focalLengthMm,
        public readonly float $aperture,
        public readonly DOFLevel $dof,
        public readonly CameraHeight $startHeight,
        public readonly CameraHeight $endHeight,
        public readonly CameraMovementType $movementType,
        public readonly array $velocityCurve,
        public readonly FramingType $framing,
        public readonly string $movementMotivation,
        public readonly float $estimatedDistanceM,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            shotId: $data['shotId'],
            focalLengthMm: $data['focalLengthMm'],
            aperture: $data['aperture'],
            dof: DOFLevel::from($data['dof']),
            startHeight: CameraHeight::from($data['startHeight']),
            endHeight: CameraHeight::from($data['endHeight']),
            movementType: CameraMovementType::from($data['movementType']),
            velocityCurve: $data['velocityCurve'] ?? [],
            framing: FramingType::from($data['framing']),
            movementMotivation: $data['movementMotivation'],
            estimatedDistanceM: $data['estimatedDistanceM'],
        );
    }

    public function toArray(): array
    {
        return [
            'shotId' => $this->shotId,
            'focalLengthMm' => $this->focalLengthMm,
            'aperture' => $this->aperture,
            'dof' => $this->dof->value,
            'startHeight' => $this->startHeight->value,
            'endHeight' => $this->endHeight->value,
            'movementType' => $this->movementType->value,
            'velocityCurve' => $this->velocityCurve,
            'framing' => $this->framing->value,
            'movementMotivation' => $this->movementMotivation,
            'estimatedDistanceM' => $this->estimatedDistanceM,
        ];
    }}
