<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Ir;

use App\Services\AI\AFOS\Types\NegativeSpaceDirection;
use App\Services\AI\AFOS\Types\CompositionRule;
use App\Services\AI\AFOS\Types\EyeFlowDirection;

final class CompositionIR
{
    public function __construct(
        public readonly string $shotId,
        public readonly string $primarySubjectEntity,
        public readonly float $primarySubjectFrameX,
        public readonly float $primarySubjectFrameY,
        public readonly float $primarySubjectScale,
        public readonly NegativeSpaceDirection $negativeSpaceDirection,
        public readonly float $negativeSpaceAmount,
        public readonly ?string $foregroundEntity,
        public readonly ?string $midgroundEntity,
        public readonly ?string $backgroundEntity,
        public readonly CompositionRule $compositionRule,
        public readonly EyeFlowDirection $eyeFlowDirection,
        public readonly string $decisionRationale,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            shotId: $data['shotId'],
            primarySubjectEntity: $data['primarySubjectEntity'],
            primarySubjectFrameX: $data['primarySubjectFrameX'],
            primarySubjectFrameY: $data['primarySubjectFrameY'],
            primarySubjectScale: $data['primarySubjectScale'],
            negativeSpaceDirection: NegativeSpaceDirection::from($data['negativeSpaceDirection']),
            negativeSpaceAmount: $data['negativeSpaceAmount'],
            foregroundEntity: $data['foregroundEntity'] ?? null,
            midgroundEntity: $data['midgroundEntity'] ?? null,
            backgroundEntity: $data['backgroundEntity'] ?? null,
            compositionRule: CompositionRule::from($data['compositionRule']),
            eyeFlowDirection: EyeFlowDirection::from($data['eyeFlowDirection']),
            decisionRationale: $data['decisionRationale'],
        );
    }

    public function toArray(): array
    {
        return [
            'shotId' => $this->shotId,
            'primarySubjectEntity' => $this->primarySubjectEntity,
            'primarySubjectFrameX' => $this->primarySubjectFrameX,
            'primarySubjectFrameY' => $this->primarySubjectFrameY,
            'primarySubjectScale' => $this->primarySubjectScale,
            'negativeSpaceDirection' => $this->negativeSpaceDirection->value,
            'negativeSpaceAmount' => $this->negativeSpaceAmount,
            'foregroundEntity' => $this->foregroundEntity,
            'midgroundEntity' => $this->midgroundEntity,
            'backgroundEntity' => $this->backgroundEntity,
            'compositionRule' => $this->compositionRule->value,
            'eyeFlowDirection' => $this->eyeFlowDirection->value,
            'decisionRationale' => $this->decisionRationale,
        ];
    }}
