<?php

// ┌─────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED — do not edit this file manually                 │
// │ Source: resources/afos/schema.yaml                              │
// │ Regenerate: php artisan afos:generate                           │
// └─────────────────────────────────────────────────────────────────┘

namespace App\Services\AI\AFOS\Ir;

use App\Services\AI\AFOS\Types\GoalType;
use App\Services\AI\AFOS\Types\Emotion;
use App\Services\AI\AFOS\Types\NarrativeFunction;

final class ShotGoalIR
{
    public function __construct(
        public readonly string $shotId,
        public readonly float $durationSec,
        public readonly GoalType $goalType,
        public readonly string $goalTarget,
        public readonly array $viewerShouldNotice,
        public readonly array $viewerShouldIgnore,
        public readonly Emotion $emotion,
        public readonly float $energy,
        public readonly NarrativeFunction $narrativeFunction,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            shotId: $data['shotId'],
            durationSec: $data['durationSec'],
            goalType: GoalType::from($data['goalType']),
            goalTarget: $data['goalTarget'],
            viewerShouldNotice: $data['viewerShouldNotice'] ?? [],
            viewerShouldIgnore: $data['viewerShouldIgnore'] ?? [],
            emotion: Emotion::from($data['emotion']),
            energy: $data['energy'],
            narrativeFunction: NarrativeFunction::from($data['narrativeFunction']),
        );
    }

    public function toArray(): array
    {
        return [
            'shotId' => $this->shotId,
            'durationSec' => $this->durationSec,
            'goalType' => $this->goalType->value,
            'goalTarget' => $this->goalTarget,
            'viewerShouldNotice' => $this->viewerShouldNotice,
            'viewerShouldIgnore' => $this->viewerShouldIgnore,
            'emotion' => $this->emotion->value,
            'energy' => $this->energy,
            'narrativeFunction' => $this->narrativeFunction->value,
        ];
    }}
