<?php

declare(strict_types=1);

namespace Tests\Unit\FilmOS\Golden;

use App\Services\AI\FilmOS\Render\RenderIR;
use PHPUnit\Framework\TestCase;

/**
 * Golden contract tests for the RenderIR → Provider payload serialization.
 *
 * Each fixture pair locks:
 *   - render_ir.json        →  INPUT (generated by GoldenCompilationTest)
 *   - kling_payload.json    →  EXPECTED Kling API payload
 *
 * Activated in Sprint C.2 when KlingSerializer is implemented.
 *
 * Regenerate kling_payload.json fixtures after an intentional change:
 *   FILMOS_UPDATE_SNAPSHOTS=1 php artisan test tests/Unit/FilmOS/Golden/GoldenSerializerTest.php
 */
final class GoldenSerializerTest extends TestCase
{
    private const GOLDEN_DIR   = __DIR__ . '/../../../../resources/filmos/golden';
    private const UPDATE_ENV   = 'FILMOS_UPDATE_SNAPSHOTS';
    private const SERIALIZER   = \App\Services\AI\FilmOS\Render\Serializers\KlingSerializer::class;

    protected function setUp(): void
    {
        if (!class_exists(self::SERIALIZER)) {
            $this->markTestSkipped('KlingSerializer not yet implemented — activate in Sprint C.2');
        }
    }

    // ── Kling payload snapshot tests ──────────────────────────────────────────

    /** @test */
    public function sports_touchdown_renders_expected_kling_payload(): void
    {
        $this->assertGoldenSerialization('sports_touchdown');
    }

    /** @test */
    public function breaking_news_renders_expected_kling_payload(): void
    {
        $this->assertGoldenSerialization('breaking_news');
    }

    /** @test */
    public function finance_renders_expected_kling_payload(): void
    {
        $this->assertGoldenSerialization('finance');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function assertGoldenSerialization(string $domain): void
    {
        $dir        = self::GOLDEN_DIR . "/{$domain}";
        $renderIr   = $this->loadRenderIR($dir . '/render_ir.json');
        $serializer = new (self::SERIALIZER)();
        $actual     = $serializer->serialize($renderIr);

        $fixturePath = $dir . '/kling_payload.json';

        if (getenv(self::UPDATE_ENV)) {
            file_put_contents(
                $fixturePath,
                json_encode($actual, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . "\n",
            );
            $this->addToAssertionCount(1);
            return;
        }

        $this->assertFileExists($fixturePath,
            "Fixture missing: run with FILMOS_UPDATE_SNAPSHOTS=1 to generate kling_payload.json for {$domain}");

        $expected = json_decode(file_get_contents($fixturePath), true);

        $this->assertEquals($expected, $actual,
            "Kling payload snapshot mismatch for [{$domain}].\n" .
            "Run with FILMOS_UPDATE_SNAPSHOTS=1 if the change is intentional.");
    }

    private function loadRenderIR(string $path): RenderIR
    {
        $data = json_decode(file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);

        return new RenderIR(
            traceId:            (string) $data['traceId'],
            version:            (int) $data['version'],
            shotId:             (string) $data['shotId'],
            durationSeconds:    (int) $data['durationSeconds'],
            renderInstructions: $data['renderInstructions'] ?? [],
            constraints:        $data['constraints']        ?? [],
            metadata:           $data['metadata']           ?? [],
            attributes:         $data['attributes']         ?? [],
        );
    }
}
