<?php

declare(strict_types=1);

namespace App\Services\AI\FilmOS\Narrative\Production;

/**
 * The complete staging plan for a production — the payload of
 * ProductionPlannedEvent and the state behind ProductionProjection.
 *
 * Authored by humans in v1 (scenario author IS the director planner);
 * generated by a Director Planner once benchmark data says which
 * decisions are worth learning ("benchmark before intelligence").
 *
 * Immutable.
 */
final class ProductionPlan
{
    /**
     * @param VisualMotif[]      $motifs
     * @param VisualConstraint[] $constraints
     * @param EnergyPoint[]      $energyPoints
     * @param ShotTiming[]       $timings
     */
    public function __construct(
        public readonly ?DirectorIntent $intent       = null,
        public readonly ?ConflictPlan   $conflictPlan = null,
        public readonly array           $motifs       = [],
        public readonly array           $constraints  = [],
        public readonly ?HeroMoment     $heroMoment   = null,
        public readonly array           $energyPoints = [],
        public readonly array           $timings      = [],
    ) {}
}
